apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: homarr
type: Opaque
stringData:
    SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:Z0r4ZcUZjy9vBKdubBL8h7WpspIke1TPGpY8l5ihlWBqVNhohYnVOGP8beEQ9IVeQ3hVncEPDXHoWNXzicqC/A==,iv:F3MUYyDivEp7GwIhv3x1/HXI4ub7bsSxQwpt8M81Psg=,tag:U7KGjbcD32X8bSilrprgLA==,type:str]
    db-url: ENC[AES256_GCM,data:gwMDXxJluLufO9xFIhyXhKRytkw=,iv:mBHOJYIeonVBxOPPi3DFFVFlTm6zsehq8ctnrJDECkE=,tag:/9RBUtlDDS2KFr/vFRIjjw==,type:str]
    mysql-root-password: ENC[AES256_GCM,data:m27MceR+BSpKGE+BuOnoGO6tHETdjaY7,iv:Ab5GA13PmNK2mCY9ZTWSJqq7zCoGdylArQXy2kReGv0=,tag:4BfDxsGDPKzyXI4MiS2vkA==,type:str]
    mysql-password: ENC[AES256_GCM,data:4AvZp8Foqa0I+IaYqGTzEvimMdqxVpJE,iv:vbYakroEeQ0wmMV+TtbWJ9rTQ9+IDBMSCyyqUFIh7m0=,tag:vXD5SafpPlxTCAxRMFyLZw==,type:str]
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Q0ZKckZrWDZNRnhldGpQ
            T1F5VXFGZXI0OVBsN2tRRGpMNnZtQ0s4RnlrClc2Zmo2TGtFVE5kRFZaVE45UWlz
            NUpHRGdDdmcyMnlGTDBCVjBmWncyZ00KLS0tIDFka2tscEExaXBSdXJBUTdrT2dZ
            dXVoWVVsZm12d2lja1g4d1JjbXlnV00KnUiC390T90k5Hn/vjEB/nEAMh2h+TpHM
            sN88f+UE0OGsURr1hnPVSosTLI9Q/gyR7JnXtFmpeBeXt1NLltYbhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-11T05:09:04Z"
    mac: ENC[AES256_GCM,data:b3p7+O5WJssftFeZ2E8ccwswMbHTJpdBOp75XIY6vvIxZ5/sSA6evmBQ6/ca2dw7SUKvbBV3eILS7aGh7CG3NXE1mf/3A81ayje47+nxIipBjrWTvVfo7L6WrB6hSbwJmagx4YrHomeTp2c4nl4EKcHTAFl3PxIAXa7xfVSc5S8=,iv:Hpc+9Z44lL9mwsvvOFdl/zU223dLvQCaODuBOXBk5Tg=,tag:RhLwgET7XPnofAYjMbNm5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
