apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homarr
resources:
  - ../../base/homarr/
  - cloudflare-secret.yaml
  - cloudflare.yaml
  - db-secret.yaml
  - values-patch.yaml
