apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 30m
  chart:
    spec:
      chart: homarr
      version: "5.x"
      sourceRef:
        kind: HelmRepository
        name: homarr
        namespace: homarr
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    # Base configuration
    image:
      repository: ghcr.io/homarr-labs/homarr
      tag: "v1.26.0"
      pullPolicy: IfNotPresent
    
    replicaCount: 1
    
    service:
      enabled: true
      type: ClusterIP
      ports:
        app:
          port: 7575
          protocol: TCP
          targetPort: http
    
    containerPorts:
      http:
        port: 7575
        protocol: TCP
    
    # Reference ConfigMap for environment variables
    envFrom:
      - configMapRef:
          name: homarr-config
    
    # DISABLE MySQL - Homarr uses SQLite by default
    mysql:
      enabled: false
    
    # Database configuration - using SQLite (default)
    database:
      externalDatabaseEnabled: false
      migrationEnabled: true
    
    # Correct persistence configuration based on Dockerfile
    persistence:
      # Main data volume for SQLite database (/data)
      homarrDatabase:
        enabled: true
        existingClaim: homarr-data-pvc
        mountPath: /data
      
      # Config volume for configuration files (/app/data/configs)
      homarrImages:
        enabled: true
        existingClaim: homarr-configs-pvc
        mountPath: /app/data/configs
    
    # Health checks
    livenessProbe:
      httpGet:
        path: "/"
        port: 7575
      initialDelaySeconds: 30
      timeoutSeconds: 5
    
    readinessProbe:
      httpGet:
        path: "/"
        port: 7575
      initialDelaySeconds: 10
      timeoutSeconds: 5
    
    # Resource limits
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    
    # Security context
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
