apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 30m
  chart:
    spec:
      chart: homarr
      version: "5.x"
      sourceRef:
        kind: HelmRepository
        name: homarr
        namespace: homarr
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    # Base configuration
    image:
      repository: ghcr.io/homarr-labs/homarr
      tag: "v1.26.0"
      pullPolicy: IfNotPresent
    
    replicaCount: 1
    
    service:
      enabled: true
      type: ClusterIP
      ports:
        app:
          port: 7575
          protocol: TCP
          targetPort: http
    
    containerPorts:
      http:
        port: 7575
        protocol: TCP
    
    # Reference ConfigMap for basic config
    envFrom:
      - configMapRef:
          name: homarr-config
    
    # REFERENCE THE SECRET HERE!
    envSecrets:
      dbCredentials:
        existingSecret: "db-secret"        # This points to our secret
        dbEncryptionKey: "enctryption-key"  # Key from secret
        dbUrlKey: "db-url"                    # Key from secret
        dbPasswordKey: "mysql-root-password"  # Required by chart
        dbUserPasswordKey: "mysql-password"   # Required by chart
    
    # DISABLE MySQL
    mysql:
      enabled: false
    
    # Database configuration
    database:
      externalDatabaseEnabled: false
      migrationEnabled: true
    
    # Persistence for SQLite
    persistence:
      homarrDatabase:
        enabled: true
        existingClaim: homarr-data-pvc
        mountPath: /data
    
    # Health checks
    livenessProbe:
      httpGet:
        path: /api/health/live
        port: 7575
    
    readinessProbe:
      httpGet:
        path: /api/health/ready
        port: 7575
    
    # Resource limits
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"