apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 30m
  chart:
    spec:
      chart: homarr
      version: "5.x"
      sourceRef:
        kind: HelmRepository
        name: homarr
        namespace: homarr
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    # Base configuration
    image:
      repository: ghcr.io/homarr-labs/homarr
      tag: "v1.26.0"
      pullPolicy: IfNotPresent
    
    replicaCount: 1
    
    service:
      enabled: true
      type: ClusterIP
      ports:
        app:
          port: 7575
          protocol: TCP
          targetPort: http
    
    containerPorts:
      http:
        port: 7575
        protocol: TCP
    
    # Reference ConfigMap for environment variables
    envFrom:
      - configMapRef:
          name: homarr-config
    
    # Database configuration - using MySQL
    database:
      externalDatabaseEnabled: false
      migrationEnabled: true
    
    # MySQL dependency configuration (from Bitnami chart)
    mysql:
      enabled: true
      auth:
        database: homarrdb
        username: homarr
        existingSecret: db-secret
        secretKeys:
          adminPassword: mysql-root-password
          userPassword: mysql-password
      primary:
        persistence:
          enabled: true
          # Try without existingClaim first - let chart create PVC
          size: 5Gi
          storageClass: "local-path"
    
    # Homarr data persistence
    persistence:
      homarrDatabase:
        enabled: false  # Disabled because we're using MySQL
      
      # Enable persistence for images/icons
      homarrImages:
        enabled: true
        # Try without existingClaim first - let chart create PVC
        size: "2Gi"
        accessMode: "ReadWriteOnce"
        storageClass: "local-path"
    
    # Health checks
    livenessProbe:
      httpGet:
        path: "/api/health/live"
        port: 7575
    
    readinessProbe:
      httpGet:
        path: "/api/health/ready"
        port: 7575
    
    # Resource limits
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    
    # Simple security context - no user changes
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false