apiVersion: v1
kind: Service
metadata:
  name: headlamp
  labels:
    app.kubernetes.io/name: headlamp
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: headlamp
  ports:
    - name: http
      port: 4466
      targetPort: http
      protocol: TCP
