apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
  name: mealie 
  namespace: mealie  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      securityContext:
        runAsUser: 911
        runAsGroup: 911
        fsGroup: 911
      containers:
        - image: ghcr.io/mealie-recipes/mealie:v2.8.0 
          name: mealie
          ports: 
            - containerPort: 9000
          env:
            - name: NLTK_DATA
              value: "/app/data/nltk_data"  
          volumeMounts:
          - mountPath: /app/data
            name: mealie-data  
      restartPolicy: Always
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data