apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
data:
  # Database configuration
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: "n8n-postgresql-cluster-rw.n8n.svc.cluster.local"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: "n8n"
  
  # n8n application configuration
  N8N_PROTOCOL: "http"
  N8N_PORT: "5678"
  N8N_HOST: "n8n.watarystack.org"  # Replace with your actual domain
  WEBHOOK_URL: "https://n8n.watarystack.org/"  # Replace with your actual domain
  
  # Additional n8n configuration
  N8N_METRICS: "true"
  N8N_LOG_LEVEL: "info"
  N8N_LOG_OUTPUT: "console"
  EXECUTIONS_DATA_PRUNE: "true"
  EXECUTIONS_DATA_MAX_AGE: "336"  # 14 days in hours
  
  # Security settings
  N8N_SECURE_COOKIE: "true"
  N8N_BASIC_AUTH_ACTIVE: "false"
  
  # Workflow settings
  WORKFLOWS_DEFAULT_NAME: "My Workflow"
  N8N_DEFAULT_BINARY_DATA_MODE: "filesystem"
  
  # Editor settings
  N8N_PERSONALIZATION_ENABLED: "true"
  N8N_VERSION_NOTIFICATIONS_ENABLED: "true"
  
  # Performance settings
  EXECUTIONS_PROCESS: "main"
  EXECUTIONS_MODE: "regular"
