apiVersion: v1
kind: Secret
metadata:
    name: linkding-backup-s3-secret
    namespace: linkding
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:J95iWzivgf7ZKNosun+xoyC2xzxEPlnjlyvWreLCHH0=,iv:9OekLgtoohkIwm6b7qIvELptcXcwgeLtDHMDStugzP0=,tag:aEMrdHdPm9EsVicggMrjzQ==,type:str]
    ACCESS_KEY_SECRET: ENC[AES256_GCM,data:AhUcbhTEtLDjiNA9ReYEpF44ezIv2E35CwDtqKACldkIwwrjC/5DbQ2O9qlyr8RWJcyYAj1Bl5ghVaDsT05GyQ==,iv:ThG7jutPJ7lzwEJTg8IavkOrxEwLgmuqlMxezkJNfoM=,tag:72nY9ObsS85S5sQbqd7ReQ==,type:str]
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVW05UWF6TTRQTGFoS3RN
            TWtPeDRwaGhXOGorV1JDNEltcENBZjczR1dNCjhDNkdsMm1WK3B0QmhNajd5UWNk
            RHZURGFlL0taVm1WMDdSaVFvMlZxOHMKLS0tIGRaTkhqYUtBTHVKR09EYVVqMUpy
            cnVBdVduc0VrakNIRW1jajJCNFdvZ2MKkD5i9M+b4vDH07eS0BQ9VkOaf9/xuZpw
            okfrqaFjXrXHYGSWmSwhMrBxJJuRYxmaqY62sUfLov0jsenD6Q9ipw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T01:17:27Z"
    mac: ENC[AES256_GCM,data:wYE+51oxcUznrZuADxi2JlTp8JiqW5cdD65NroJOQr7DJReARmkiNcz+l0wU1WytlMbhtMyJBsv00x5iMkPB6h5P71l0b7xay8E25YbO3waPqjUyhk1qlsb6pgBjScwBOjMxogVTQlKZL2ccx1E3u4nOvJtNWYDCGGUu1eDJvkM=,iv:rccE6eb8ZXbH2qgx1vCBdFZ6GHlXO5BvsIWm4XKBENk=,tag:QbKOd4Ox11SEBxBQLAAzpw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
