apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-postgres
  namespace: linkding
spec:
  description: "PostgreSQL cluster for Linkding application"
  instances: 1
  
  # Enable monitoring with service
  monitoring:
    enabled: true
    podMonitorEnabled: true
    
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"
      effective_cache_size: "512MB"
  
  storage:
    size: 2Gi
    # storageClass: ""
  
  superuserSecret:
    name: linkding-superuser
  
  bootstrap:
    initdb:
      database: linkding
      owner: linkding
      secret:
        name: linkding-db-credentials