apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:WfPIrAlXLp1iRiU/Uvxu+5LVxG8JF5JKujRBxbtza1Z/R8lC5id2h1+e7IOvASKmhq3w1lW/x2NCXqNbblQkaHt6DBQEd3GOvMZ4b2+F751aksMHLkvoW6aFHegNpffKusd/Bvq9bVcgtS0Rb+mY5UaVE1EOfJ5hZvb6tZlaZSD6Ub0B6XBvwXtEcdyd6fUXUDpk1Q7/XL30rZbAK/h6V36IlZ2C/4Eh81Llb/znNsa1cNnDj8+5RmnVBiXa90yJNzWkRtaJOKrmkuPut5wXFlQ6cLS33Zc68b07ArBO57qM0yRJwhzInO+Lw9A=,iv:hlZgpXqLjoAamx3oglnAkoCupK5S8Ntr4SeX1GzO62I=,tag:GR7XQMfoUwV6d/oGwBlvdA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZ1E2WmEyazFuN2hKS3Qr
            QkY5Zk5UdGpQNkpqZDhnMDhKQVRMYVhrVVQ0CmhERlliWldBa0RTKytpenUvaVBN
            VXJRbmVGM2E1L1BaWFpmaFpldE9BY0EKLS0tIDcxcytuQzFWMUNJcmdMMzA0bm53
            aFU1RVhGa09mMkVveHNwekVUNDJncmsKrqFjzmgDEKHcRXXjDx1OD96dpFSnYjR8
            BmzZ6BvW9ME0esy2A09XnM27FsyhIhH9u674+3yXLFTMgWVIek03AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T07:28:15Z"
    mac: ENC[AES256_GCM,data:hasVNUoB37XoOIz7sy6dKn9dghCRCLSQE+A0hVJFHKgtnv0NUNoAjeeAp32lB3Pm/YGDbVRd7eEI97MzvTAsRYIVNdecGMnhsqKZizeG6PwodLCEyYhRrawI1QybEzjTu1DtdeCxy5ekDWWbnHD2q8wTl5P6W0LLEnVwxeCb0Sg=,iv:M6Nfb3QBxycJyju+yysVE+Ao09++M3fS7QmWdKyipc8=,tag:Ym4zLUhO+J1y1dcvlvaNqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
