apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
data:
    #ENC[AES256_GCM,data:QlMs1kuSP3YLnjcURs36ed1h6NIyEs0IJw==,iv:zk0ot9Qicg7eVhOHLLaO/W3do6R/j0csTB7sLcOFGAI=,tag:++of5+I28yKfnl/jKz1P3A==,type:comment]
    api-token: ENC[AES256_GCM,data:Sgx3eo6ODU4Unme612CmIm0a9cw/YpmChyacONwBYuG6wEIWTYD0e8G/e/+hbzGR30szgN70JbI=,iv:2oEhbSROFkmJvxRnzpE5p0r9BW42WIRKwsNJaAQ49EU=,tag:zMQcUmB1E6W+LhKsi6M8cg==,type:str]
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaDBTcmZqUlNxbmtlbU9p
            aFFuWE1EdEZHajBrQ1ZEbmhKcE16b2trY3lZCklzbTIyUjRzbG1xNFpvODFCOU1t
            c1pSQTRrYnNBQlB6NFpZL1I3YnhpODAKLS0tIExZUU4xbTRCdlk4by84MEE1czYx
            Z3pHTDdIYjcyc3E0Qi80cXZtNWZpV0UKZrWyljIebfqf6gaPhLvTv8MvVDjCBC1n
            yDxksjF4a7bWQlQ8WmiDpc0hd2SquoNhO47SLeqhxIfXHex7IXPX9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-06T21:57:54Z"
    mac: ENC[AES256_GCM,data:xW8mjMjyxNMQvdgbdEVWFeUXWdtWkLYNHfXHtvlUzA/Rqo8f2ovdZTsxLK1cJEGyJtRFUZV2oEayUbWAfojwPidRi0dwqzsIzt0qkJFr/cGV7z93aSxFWA6R8O6jijIPPDZCV7uh9y8yC+t5IbzSacM3apX+MDmIfKqB36U+n88=,iv:34/ID4SElAuNraxiw8HV1vu+7QqAEu5QAwvT6T3+NM4=,tag:F8tuSXBx9szfuqijG46atg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
