apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:4gxxdoIeYyJ4nqMtmhdnojGcUNjOXRTM95CX55kO1OStSQjIiiAOC+H70F4JFzLuT1QEWguIbY+G2KfxQjaaGp3N4GjKSX/Vtkce3Re3bjUP/BZNkMm17LOLvw5qt63zreRt9dkArt578wwh0v4GXLGZzUQ+lXvkKidTUMxisZGUnwuETovcArhwOpZbS7q/gDqz+3rJYZZ1Ax3vfnMP1oSwjfzkNMRbWoxOsDgsHdeGHiKhHB7H+itxdEymLufKFAZe1O44Q2uPa5UE7MK1DU+LisnFUiiK0B91qWt/Mk1hqQ7elVXHU5OWS/w=,iv:MV+gN/t90BntKuWezMQH/AZaOlV88F2l/xtwlaWUsWY=,tag:a895ojaXwIml8CcrBvoIkA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdFJrbVhIcTBUY0pTKzlk
            MGRvbXgvV0lQZHFxanY5ZE9XZmdaUFdaWjBnCk9wVFlxMnVRaVh3ZklBaDAvWStB
            YlRlaEtNTGEyRWFTYTJ3RVVVcmEvYWMKLS0tIDQrOE9XMEEvbjJ3N0JVeWdjUTYv
            NmM1UE9hbDF6ajk2NVh0bklFUTdtRWMKkh9m13QuMKgy1ckUrpqnoEQjUEN1C/rv
            sJqdUczsUYHr2t0vmPTh6OQoI31ymxTHtRDRKiZZCDkNDuR8t/PLJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T21:42:12Z"
    mac: ENC[AES256_GCM,data:BJECBbvQcohgGshVjRDN6UgXz35vY5qvjFCwtFDqIYM7n6Ymxb08K0wOKN88x7QHCSThaE7MFOB4WU9Azez8GLsyC8ekjaRomdi7bfANeuiXGrM+r00yPr3GVbmHgXhr4zC/JYTdijp18PdTsUOHsNjbjV95oZrpwStMEx5NVRI=,iv:CfJSYr2iV50SFtav553NXtBIZlxjwcIQzLwHm4ofbJw=,tag:y/eMIktokoeF83FjLhvRzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
