apiVersion: v1
data:
    FB_PASSWORD: ENC[AES256_GCM,data:bmtuyCckBaBoIBppwmwrMP4nNFWXRvuQbJHnYYdl6+185GctBOI2Pw==,iv:QrUYaxbE+XHRR050uUUGx4Fa9hNk9NKvx55SVGHawR4=,tag:s7mn0bIgNPHSGBM70dXJGA==,type:str]
    FB_USERNAME: ENC[AES256_GCM,data:WXEG0umw1koLrsNR9w1RJzHGDHs=,iv:gpQESsbCiHL63+Hnv1PA9uepRBZV5Uh/bTpToQOYYGk=,tag:mWL13EMmGemehMNci2qVvA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: filebrowser-env-secret
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRGprbXoxcU1pTXlWTHh5
            ZCtkdVF1c1VPNzBLMXU2Q1RtSXFsU1p2ZkEwCjhyUDNFbjArd3VYUzhxN2xQWk4x
            eCtEY3N1YkxmREVJd0p2Y0Y1ZldpNEUKLS0tIE5LN2gxZGJZQ0lLMzB3T2RvTmNH
            SzlEOGlvOVdPY1JaN01zTFBiVm5kU2cKcF6y++0B26WLpquxVuWIUk/5E11pW0pP
            xZnSEoi7BEPTJ1c4S4qYmQ0pnPvgDYPWJ/wLnXcFEiiJENT9W5HPTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T21:42:12Z"
    mac: ENC[AES256_GCM,data:Ndz4PvXegyQH7vDIM8k59YaBjjjUUhj6HbWjgU3ZHisAyW72qMKmU88ZOU66bNNFmd+S10AW7m8QlSjR3P+zVPatkhcIpHqYGPbQ/6/1DMV5IFpdKjCjZRlW5EGpBn56tzcte5Acui0HvWKitAx6m44lf73HjRCsXkPcK4xEQuw=,iv:R7vLJ1L/+V2bv2xVDMLlYSXNEaYLqR+iKNlzSDgxtVA=,tag:zn5BfPXJw6F/aIorJKaZpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
