apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:EI8gwlhDVRnkiiXOkUkQdv43FMLkRYVYgis+ZSbxJOhP6bDkSxSKY4DdOyw=,iv:v33FnftfRIObca7HV30oLf+WyMXCuLG0XXlDAneM368=,tag:0gdXZCRTpvM55+8xKKBvdQ==,type:str]
    ACCESS_KEY_SECRET: ENC[AES256_GCM,data:z8DxaoyvSP+DGRC2dR4XZX0Ruyg8AEsAM7XRCMNSKh3/BHNZ5cB/8GfhnWiiBnn3OOAR9s6edelHNQfaZ9rmbqIGVfhzn3anQJTokyG+s6HZW6OMsWbIFg==,iv:UXC0mpMdqUcRqw+BYg9J4nV6k8q3IhotjXxKs80Bvps=,tag:ODhGaOdixRzxSu229d8YwA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: forgejo-backup-s3-secret
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrLzRBY2ZSUWx6RE9tdXV3
            YXIxTTZmWFBFNE1kczBVS2tmL2xZY1A2MGlvCmJKRjhxbEtZSTNjZnAySHNidFV5
            M1BIQVM2Nzd0YlZSY1pWbG5DNjB0aW8KLS0tIFFta1VBZ2o1UGJnTUdtTWhYWDRu
            WVN5cmtuelo1TmdrMDNJUTZKZWhPN3cKtZT+Ry3jYUkNpzjGgBHfmHmyIGneW6Y8
            1BFR1W0fFesuhKztHfxgUbq1aY8QrTELtnTULy0VZk/bXfW6BQliYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T23:21:12Z"
    mac: ENC[AES256_GCM,data:54K2O0SQaEM7zMocxy5uSL5on3U1S/zsdJMADmOP7MFvk0UqDemJvNzeYl3CoEKB+TDtZwxKPW9vPiTNMws3+Qja8vsbT8Sh+kgGRlpNkOKYKRobAWlb8C8XxmASYUZQIXaQdOsktnsLbaTXQGcwHs2cLPCkvt1UaKFh2vTxhic=,iv:Y8hdf3izoljj2Ed9jEZyPXzB6d7kDkfD4Jh9r1q1upk=,tag:xmziiXJcnbo787qjuGGvmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
