apiVersion: v1
data:
    password: ENC[AES256_GCM,data:74IPbgXQnWKI2m9HejzEMaK4+kQ6/cqSr21G+F8S5+G8xCX1H2sBZg==,iv:QG5VpS7EZTFZvQhGiCTtRZW2ZXz1x/xVPvZ6r50cqa4=,tag:XzW6dOZxNG44pNKEFoOyBw==,type:str]
    username: ENC[AES256_GCM,data:UCH5xdL6qxzpFmCf,iv:r/ieQraUvengs5GbQJIZHuis6IbqmBFwmm1G9O2UlLg=,tag:IENrzir8rrZzcLe3f32sAw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: forgejo-db-credentials
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RU1aNktEVStqMTd4MlFK
            YVdXTTdzbDdXWVlqNCt2MTdycHl0UGowQ2s4CmdVTVp2R0ZFS05lN25yT1B2NWIz
            bVRZclJObUZxK0dwcFRxQmxoYitNekkKLS0tIE1MTGxjc3VIN1JLZzRxYzVadmd4
            VXoycVRMOXFyVjA0amdCWVJiL2I1N2sKDMuPlsLLmR6+2UkMprZ28ZcE2w2iRZeJ
            HjkOy0rKMeQKDg4AU+J0lgA4r6JborEqNpAp6M7zlLkJIXqjjc2H2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T23:21:12Z"
    mac: ENC[AES256_GCM,data:LO0ZCUO0ddHG6RFzsOSqS5m1WoCArquX5CBX4uh/48FIg1r4mT51FNwIsvIOUf/gXvx+bsw3DME7RIubSTqDzKsgo61NmsrzCqFiPmcfAo3g0jQkWhHRs6kwHEE8nafwSM+a7v2/uC2HLDlh+6n0HPXb6fes1u098MEUYZsVCro=,iv:7lc/gpyooBygxIhHthJHM967u+CU1h7h+BzAWPEhuFc=,tag:VFYOUpAv1rVLo24to3itVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
