apiVersion: v1
data:
    password: ENC[AES256_GCM,data:hIkl1r1uoQNU820bKxEFdDAwpwDyh+bUW+I20uXTgnpRIG+JfV9XU1SEfpg=,iv:fDIMmyuTY+0ZjaUNsJXh12DJ9TURZeAXR/hoVu9qwps=,tag:e9hNoHh0ay8Pyf3+WPTobQ==,type:str]
    username: ENC[AES256_GCM,data:WaR5Mz2ZnCZ7iaEI,iv:le2MD1WYmanUZvEwFqyACHz2fJ1vUC6+A3WlcCPSRug=,tag:lC/CtEddxRzxmYZuvKY2jA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: forgejo-superuser
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUThyM3RYalNLQkdtZmhv
            SUpLYXpZbVRyVmhtUWNHN2VOeDAxUHVTaTAwCk92WTcxdUZhOEF4TU9IN0UwNjMz
            czUxTnBjSENMbjJ4ZTIxTkpqRDRuUWsKLS0tIGYvNVZDbmRCSEpFdXFYeDlHQzhj
            Q05BMXZwaHUvc0RMSUxqR1Fidmc4ajgKKEz1JGKWp0KVNXqOIumunQQhOjI8coDL
            k/AJWgMAlPV1CSHo2CnTvJQP/vHgTVBydpsncH/I4c3bwcC/4CNT+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T23:21:12Z"
    mac: ENC[AES256_GCM,data:6MY9ou5S/cESSZ+uurOj+BOKIzdzAJNPjMvvdohsOfaf6QKefdbmrkcfpFV7G+YrYBnv0DpucuIGwG9ag27yk6XbYXz16P8+VOXwcC71uWcl+Lqpk8pNRdeW3830JBS4Tu+wgzQDNaR62ZDoii3rSCtfNmopsGxiVvVKZe0PKbk=,iv:2ROgtoQLTMa+grQIVSewc1OWoAoDb69dXzVaiV4ZSZY=,tag:IkSwuZ7ZxwRoppSVs3poEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
