apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:q9tcp3coc7OkBy1WIoDlfZWQdijXUaXpVxl0yQhdtW/jXlNFqfxyQJY68loMmsmKE3i5yZhBrGHBrAzeqimYJQBYBTn/26OCyEIvYmMPxjaigFlNRUYZiJvtGfpaXW8CerW5ogIrmA7w7gpXbMqwaMdpS+rgMV+ShzCEdErwfYNgi3IRwhH/p9BuZX4qF9lYdyYkdA1p1MP6WVBj5T/obgJNz2W140rwSytXtK3uHPn/Lp8mTy87yYPnD7Jm6tDWTpmjwfqBoXApBuJjxGLdmx/jcd9ipJ6KNneMOuAolsd+3QDE8ROsPthJxK0=,iv:XoqelIgCe4j2bTuYoYqx/Rhe0hW7GwAzCxE0eWvI1ro=,tag:p+fVSdE9olaLGyVuuaxGYQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRN0dXMGovNnU3ZnBvaWZR
            b29LM2pzc2JsaUQzM0R4U3ZDU1d0LzJraEJNCjlvLzlwb3Z3SnM0Yk1PeVJFVkZp
            cEEwcDVia2lYTzhuNUs2U1JaNkUxNTAKLS0tIHpjcVdORFR4dVVMNU8xM2t2VVJj
            eGFDN2tsVVJxNUZUVytiRUlWWHpwc1UKEIILo6R6kXd2I6wv73XWyyWGwn4cvVOe
            eDqGGxFiYEj4Pv4raqMkjfsrIJOh2aM/G55bKD4Vz1AytK1CNBE5nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-01T22:57:32Z"
    mac: ENC[AES256_GCM,data:g3uFA7GpA8WxMKTfl+yXsAI/7p+v4zzx0HhEhT5dKzgG0Bfh49cj2minCXlH77UPUWlzIvl9w07WkRS3YuInxVOUdoW1ESxeALssg6BmJc/l7hRdvHdnLruer+gRFTQ2gFYN/WdIEKQIQzoUtL9VrYswlvP4OhQaxgS2WGElCeI=,iv:crB8ijr8aekyMHx7/wN/TBhpSimKZz0RuhuvDTkEayk=,tag:ESpLf06W7fbQwBBA311F6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
