apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-controllers
  namespace: flux-system
spec:
  interval: 1m0s
  # dependsOn:
  #   - name: infra-configs
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers/staging
  prune: true
  wait: true  # Wait for resources to be ready
  timeout: 15m  # Give it time to install
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  
