apiVersion: v1
data:
    FORGEJO_ADMIN_EMAIL: ENC[AES256_GCM,data:snuTnkidY+XenOdfFiLnYd6c/lAfzaj/c9zSIvy1eiSzzkv1rQ5g0aBWqFE=,iv:IOyo077sKdT1K4RCPM6RMYciG621Cp1xrWcZtf/oSy8=,tag:JxoubVx6snsavcxYSorGWA==,type:str]
    FORGEJO_ADMIN_PASSWORD: ENC[AES256_GCM,data:dCiw9Q2pTEBHt8RsXbLYJ12w+LJkb4mJnRYQCg==,iv:FUAdbtHyeBs4V8PeFLY+Fu1BSwXyihijyUf6XyBONHA=,tag:xbDO6uXhJiz/zu7tNzMEeA==,type:str]
    FORGEJO_ADMIN_USER: ENC[AES256_GCM,data:24k6/qnp66A=,iv:aXxCZoPg/pqLWZb5h/s+4Vr36zr6/qcK5Mufbc3AbTU=,tag:SNdD07yYHZ98uMlesUOhJw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: forgejo-env-secret
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQzlJTUxSaU84YkZsVWxK
            MGxmR1Y0TXhjbTdack1hclFFYlp6Tks0ZjM0Ck9Mc05qNjYyVzlUaTlLYlQzcXBT
            YlhjUjEwZE4wcDBHK1BlRVdXRGg1MTgKLS0tIHVDcFpEcVhhTFlyQUEvc2ZMN1o1
            SWZIZEw4TEt5KzJaVEordnpDTUxaUUkKav6RcVygdl+SNVIyLicBZddI8JnnOT9k
            g0H0GWEzhB5nLgs85txgU2c8cXFy8ePkEXsIoL6NBS6xe6/F07UXYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T23:39:24Z"
    mac: ENC[AES256_GCM,data:J8cGYGt9WQq/ztmqwRLyo8Vr3+JihLEKUwc4ArCf4aInxeH1EoIxw73C+y6YMKbF/w3xqwc3sSckl5uwrLOUFbPYNC5AtvQleRG8fkSB0M7jg/nl6znd+ipqGLfLSCAqkRBtAtAsdoYfQrEdGRJe4aaYp7hvpX4jQq4laN3eoFA=,iv:53PFtGUvUd7CFnWUbPRx96WTs+IzBEFYcPM1p9iQxUk=,tag:T1o7zPbrp6F8FvNt4q37sw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
