apiVersion: v1
data:
    FORGEJO_ADMIN_EMAIL: ENC[AES256_GCM,data:CdxdbRliJmynO+41LLdLIVOlo3GHBIbMtrRhSka3QGJqiBpRIP/L14rDUck=,iv:DB4o+jCGgjSc+a3/dpi/w6aUGJYGX2aB08gpcc6zlI4=,tag:C8kr4tWzMShh+nkySbJcdA==,type:str]
    FORGEJO_ADMIN_PASSWORD: ENC[AES256_GCM,data:PWUzjiGfHD2KLsQ71XWaBc+FmjvMRK7zvVh+4g==,iv:mEg78Nz6Ubr4EJv5iAx8k/mkyFbeHrF8BktNlSiYdeE=,tag:waB60f/5hdqFoLnSArJ+FQ==,type:str]
    FORGEJO_ADMIN_USER: ENC[AES256_GCM,data:nNulUjQ+Cxs=,iv:Rxwn4s5+yW5HO7gVeckiMdpXpRGzXjnk1KW9mtlEdB4=,tag:lCBaJYHa1rStErJYyw2vog==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: forgejo-env-secret
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMjU2c1JBY0hJcXFCOUli
            bytxOEd6U2wxUXNKYm9Cc3NPZ3d3YVM2MmtBCllRczk5NVNmblIxam1TOWFJTDVy
            cDVFcWh3Ym5rUVYybmliUlFwYzQxL0UKLS0tIFZJbitOL21ma3hubHVSTWpaWDhT
            ZU90MmNNSGlDdTlOVjZoQks3NkRYd00KTpDV/vI5lwvDRRZohE4FguYZAlMCpjL+
            uiL4mjx4zDCmbHVf71re6sv4RbrS6SfDUnz2rWOP56J6Yz+D9gAxjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T23:21:12Z"
    mac: ENC[AES256_GCM,data:Q97cZSNL98yMxUmDI53DMDbHqpX56mwZYGHqMtAaP7Hkd9KNft+GWRJkgCO5ltPyFv3AGsoyfno8tZ4mfyVdLbl4NsxgMAt9J9xLkLC5DPRWc2aV1NQuab4yrMpE3Y2+ojkLxD71RpkzmfuMYXhF24PRW2kE1xSoznWbgXvQDs0=,iv:UiMpmETdix5hs1pZ+jrYa46Q+euU1VOsVqTeC3ma7ag=,tag:UBRVp4pfxaQ3xujgmNRC4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
