apiVersion: v1
data:
    FORGEJO_ADMIN_EMAIL: ENC[AES256_GCM,data:qk2XiMDupMueebcxfZoe1jnwrJQ/CoSGIuBPHX6+N/A9vhnhxb9/+d+Wnd4=,iv:8hZ0IK0uVg6Km30q23yoZdi6YvSEU+aSbBfG15nIv5o=,tag:O0yR4sdzLsvrRw/vILnuSw==,type:str]
    FORGEJO_ADMIN_PASSWORD: ""
    FORGEJO_ADMIN_USER: ENC[AES256_GCM,data:HtMi5iOfCbY=,iv:kUXBeMadv6OYT3R30P0Bz05dMgPo+adz0QuIzRiIuOg=,tag:Q4p3Q7fQaLzTG+oJFnm0Wg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: forgejo-env-secret
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1M0hiWWJTenFrSDkvdGpa
            YW1KUndta1Y1RHRMczY4WTJ4RmIyU0s5dUMwClkrd0R0QXpGTzdCVjhKb25wK0kv
            cDh5TzV5TXJVQ1R1c0JUdGk1RG5EYTgKLS0tIFQrQW1iRGZSSUxVZ3VhRDR0c2pJ
            eHVlSm94NEl1S0EyL01SelpKOTRONDgKmjbpdQnvetHDQVyj590U3o+eN2KbELic
            N/OMHxA5Ch5uEJmGyTGHtgTQsJ4fNzs+vjluYqaMyhTxAxYXDuizgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T23:39:11Z"
    mac: ENC[AES256_GCM,data:fS4j3Hbeh0NOdIrEP7tY4reEITIgIkwxetUgDtgRWa16JovvWszejkHeK4W9otabQXjgeVdnHJGKls47O42ceRV/OSMLhVoU+oXnfZKbck92jn95Ibj0XNnfYqk4ozxM2oM4Q35OFaQ22V8hTwEitC6gNuPzQe7l1OvY+PcCn9A=,iv:GHWoFZex1wTzz3E/78Yry3qewuQeBAXx84XCnbUNAM4=,tag:EB18QdKR2YNN/PSjcXh2Sw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
