apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole
  labels:
    app.kubernetes.io/name: pihole
spec:
  ingressClassName: traefik
  rules:
    - host: pihole.internal.watarystack.org
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: pihole
                port:
                  number: 80
