apiVersion: v1
data:
    WEBPASSWORD: ENC[AES256_GCM,data:ADjzf6aHKuwTKyRXNWfSQULNAWQf8rpJjWb4KO+B2Z0gLJ8G3hUJgXV5Mnk=,iv:LfO5fOVB2vLFBYylu2za5VnMreqy785gffTQXTT6RIg=,tag:yihDxU/bF1AROY+h2KkjkQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: pihole-env-secret
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WWxwbUJqeXhpM2tMTTg4
            ZkpJYnN0L1N5TjY4Q3l2VzkxU2ZyUnhjbTFnCnpaOXQ0VEE4ak9GVUNiMWFjTTdO
            bUFPRkx1dGs2SW9HMW52VGZzb0hPL1UKLS0tIERQMUFZUS9mZzRINkpCNjZ1MFJV
            MExja0VLY1d5UEFrY1YwTTVPRU1LOGMKcj0nraENTPcjBttT7E8UXNnSvzcDFMyw
            /wGaFd2qCGryeh8UAEd9aDY/goCFsvLPCizF4wwMNysDz5ItEbSJvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T22:06:41Z"
    mac: ENC[AES256_GCM,data:umNj88ig56fsD5XEAJPnetAX7FF//6KZZxLc5wnZ/i1SosIhvBY6+QA+wnDl/bB1KdYH8iCSkQG5aqUVzYjvAlutdWHpaM4Mco22+WNKB16Z980CUOE6uekCHCe64hqxjAHuUXTTHt45R1gH1uEqU1rWQy74Xq4iCl9jjQUZrhk=,iv:GwPH93PwZRvGEICHIA4cGpUOI6BJvhj9wYVzx4gmsyM=,tag:K782Cw1Ab5Wrzdqar1wRyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
