apiVersion: v1
data:
    WEBPASSWORD: ENC[AES256_GCM,data://Ci60/N1M5foB34mCeSRVXY5mZgoIL3yx/hKw36/Xvi4KRg1YsQoJkK32Y=,iv:kJy7p5cYdUpMHIqP1NW9fTgAAB8RToX2NgZYdHzN3Qg=,tag:d98vS6ce+AEXyV9mCIpWxw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: pihole-env-secret
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxc2E2WXZzY09RSm9YbHNx
            eUhQZG01S2t5RTZuWURXTFptN0RldHhpVzJZCmRyY2NqYm5ON2dUWjFZN3N0Mi9P
            eDNzR2hWbktWZFhtdXEvakNROGxYc2cKLS0tIDRncUV4dURGbnl3MURsWmw2UzNp
            cVA3NGVzZXhMSWh0Z2FYOGdOd24zc28KWqkw8MegGqPLv5ROmUg8SYSd6o3v9GIi
            VKm6vu03MtR1IhhrtPQr/Ri5W+UDtDM2Bcd2NDUttvywWHwvfGliug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T22:13:20Z"
    mac: ENC[AES256_GCM,data:TDsoPb0UFv64GbgnS/K1ntBas7yhZ2R8PrOPciMtDPE4gkZcrDlC76YfEm9zd98H9rXkSAt14ly4TDbswYKFD/oOcqDhyrbltB7G7+Mwm07iGsgSMb/GRNlAvknhzaX74mT4pnGMfJD0rrFLU0Enk/lfeh/RKWL9+Xy9yHdVBMI=,iv:E6yKhijbZqoIHmzoqxP+4BQ74f+hL6sKcoufmi1LWLE=,tag:1paLncR6G1o7o+ikz5tLyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
