apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:V8A1NPpCJq9Smw6VzVKqMi6YsweEieO6JeQbsDEbTIDrhlqlc8Brlnj5gk/Up9WNItUevw7DkpoQRnzkXYSEksjJQTLg9Mv2zCzlF3Rb0PM+lOKBvIhlbA6dR5yJtA7gFwyrFEKaD/yr16tnx8dxxeBvTURq3yfgED18R2yRi35NLCGOLz3odHTfu449d7o4dhPL52eyPkaHCCKUyPR+YlE67jzLfkr7jlgIhMs8/ttuj5P6On3MXjnUM4aaq88DPgYghgtUakmGh6WpdsN34Y9nwkeHJXDpqaJ9epsUfyz+S2iV8GzYk00r5i8=,iv:ibxvRG5HhE53wTpXA4G6VX60NS137c8XZccIMtF/VbM=,tag:eGbo8c1Rlt7nISY9dCYzmQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva3VLbVpkZ2VUTDBlQXhI
            RjZHSzRIeGw4QzFPbkZ4NTRLQmR4VDFGdDNRCnhsQXJxbGNURVRySTBBdHA5MWNL
            SGQ5U1JtLzhCUm9zU1NTZ093cWNDU3MKLS0tIDZGeElxQUNnVGRsMnd0RzVORTVw
            dUx6V211S2pZNHdRaXp0TWpYSWF0eDgK1VbQbUjlvXMc7x5ciKt46XfHPuSnUkFw
            Enoao1e9rIgW7pwFLSIEkfPdwTUEvUZ4X2ewf2paKUZmIX60SAE0lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-03T04:14:08Z"
    mac: ENC[AES256_GCM,data:pcez3wjKiuqoM437GA8Yqn/3uW1XYKH71JvwI4QqKtg2fQSQD/BhZxWKxAgZ97phHdvRMiX+IqYamcbpQO8Eq/g0LtoJxnyzm7ow79Go3DlHI15l8T5f9GNlaJ3X+/En82frrxLAznycrHrBD59GMwKI7ZSC6Zn51NVuL0I1C/g=,iv:sK97obnuLlO4nbHmWyoVGaQHPzZESr8BqkSQ7TDmANA=,tag:M77JAjj7Cip27Rvodbrjaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
