apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
resources:
  - ../../base/n8n
  - secret.yaml
  - cloudflare-secret.yaml
  - cloudflare.yaml


# - ingress.yaml (if needed beyond Cloudflare tunnel
