apiVersion: v1
kind: Secret
metadata:
    name: n8n-app-secret
    namespace: n8n
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:UessYoFf7lWq5oXHXuJogRnnfKOh72BMoR1yEZ2xmIQ=,iv:i8XZ9Gu5zym76IoiOPhPm55lyLxY9Qx3xh9jhnORovs=,tag:69F/9zhBGKA9i0wJyrsyfA==,type:str]
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnazlQL3dNYVhVeEQ0QWVT
            ZDVod2s1S3VYSGxwdVFzMUJheUQ3WCtTd1d3ClhiVjVwNjVidE1jZXdyRUJGY1pp
            QS8rbFRGSis3dGtKYS9Ba1RLZVNndjAKLS0tIG5JRmFPQ1lZVHB0Vk04SzZYbVJ2
            S3RkSW1Ic0YvekRZSkhnS3dETm1MZFUK47U3UxndqVydK6HoCY2PBS+CBpS3x1lO
            fVtMKMqRuqUTklSJTqEZkOTtJ4N+Q7q/+pktXTlwb9FvlJ0CHah/zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-03T04:20:57Z"
    mac: ENC[AES256_GCM,data:mZZcSmK810ORqAE7boZfih6gPSa3c9vbkc7xuMxNJxtbCD7NSTkmslmoaG+wxK4Nqr+YIFYMmlUYEwZgAsn0NoX84yZ/JXOTBglGlFvs6p6+pGyH+bp0PksWpROF+pvMLfOPVOaHGmk1ut+cwokUeZVbjoVxyxDvRs8wwNvTfkM=,iv:ne0JHhOzJTESD5nxMVJKmWqYQQewFmkM88djKMuDx78=,tag:v5u5+xiEWkPU77cY7woegQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
