apiVersion: v1
kind: ConfigMap
metadata:
  name: wallabag-config
  namespace: wallabag
data:
  # Database configuration
  SYMFONY__ENV__DATABASE_DRIVER: "pdo_pgsql"
  SYMFONY__ENV__DATABASE_HOST: "wallabag-postgres-rw.wallabag.svc.cluster.local"
  SYMFONY__ENV__DATABASE_PORT: "5432"
  SYMFONY__ENV__DATABASE_NAME: "wallabag"

  # Application configuration
  SYMFONY__ENV__DOMAIN_NAME: "https://wallabag.watarystack.org"
  SYMFONY__ENV__SERVER_NAME: "WataryStack Wallabag"

  # Registration / confirmation
  SYMFONY__ENV__FOSUSER_REGISTRATION: "false"
  SYMFONY__ENV__FOSUSER_CONFIRMATION: "false"
  SYMFONY__ENV__TWOFACTOR_AUTH: "false"

  # Populate DB on first run (creates schema & default admin user)
  POPULATE_DATABASE: "true"

  # Redis disabled (single-instance homelab)
  SYMFONY__ENV__REDIS_ENABLED: "false"
