apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-images
  namespace: wallabag
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
