apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    # Add your settings here
    providers:
      # Add providers if needed
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    # Bookmarks will be configured through the UI
    []
  services.yaml: |
    - HomeLab Services:
        - Audiobookshelf:
            href: https://audiobooks.watarystack.org
            description: Audiobook and podcast server
            icon: audiobookshelf.png
        - Linkding:
            href: https://linkding.watarystack.org
            description: Bookmark manager
            icon: linkding.png
        - Mealie:
            href: https://mealie.watarystack.org
            description: Recipe manager
            icon: mealie.png
        - PgAdmin:
            href: https://pgadmin.watarystack.org
            description: PostgreSQL administration
            icon: pgadmin.png
        - Grafana:
            href: https://grafana.watarystack.org
            description: Monitoring stack
            icon: grafana.png
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "HomeLab Cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""