apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - service.yaml
  - namespace.yaml
  - deployment.yaml
  - configmap.yaml
  - homepage-configmap.yaml 
  - clusterrole.yaml