apiVersion: v1
kind: Service
metadata:
  name: pihole
  labels:
    app.kubernetes.io/name: pihole
spec:
  type: ClusterIP
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: pihole
