apiVersion: v1
kind: Secret
metadata:
    name: n8n-backup-s3-secret
    namespace: n8n
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:/K1dbElU4nx20x1P3KF87tb3TDOEHgzC5D1+tijMA3I=,iv:goVEOmFYDR/mrtsQM0UJ2eqeHWMjCOzZfnTmDwZ5bAc=,tag:2NTMzukHVDkOty/G2flihA==,type:str]
    ACCESS_KEY_SECRET: ENC[AES256_GCM,data:4JQ+X+/Y0pEwIvUAbAcMiqy6djQa4+CCDOthMDejs47maoeG7kcRgZR5EjZqEKG2NcmvJDVt9/rTx09Z9xkIcw==,iv:CanZBTXdT5c1AbOOdQADTrC7AP4Z1KOty6ze+LbWPFE=,tag:znAEXsS9Q5gS73IHTnzl3g==,type:str]
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBES0JDRlE0Q3FRNTF2UHJn
            SU5VcFhmR09YK1EycHNKaExnYlNpbFVLU3pNCnBqVGg0S2w4d0FoUU1vb0VHL0VB
            TTlRS2NJSVBQZmhSem92QXQyNnd4NFkKLS0tIE11aTBqOXlRS01wendIWkVkK0FG
            OVZMb0pKcDNVSlphWlI5NnZwc3hZejgKyQqXIJc1694oY3qW7cmNuZhzXQ7ySqZI
            r9N1X3yY7JVKl9D9Q0QBqrRk8zU4RyVQdOH6TLEU6xR0OA1MQUYvww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T01:18:11Z"
    mac: ENC[AES256_GCM,data:R3BefQQ21O4qrLgsTMnDi6vdtBoWK28qtbppmYCbMTXX5RnnrWd0g4LAE2W5m2KR7dBWJvdFviZsYaXjtH5Voa/OKp6c9taO/VK1IhzMFRPrnQi2I9sjWGtzAeMQ2Bk7Z6ZBSQotIqeVIzNweqP3uZj3eb+frMeMh4FezTaIOk0=,iv:GoL3YJ5UXoBK3RZOj0Vcxynj0lDH5ZyaGaIwnI5k1NA=,tag:LJq8cU6MdB8VRDne0gwvkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
