apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:Wu4pA9BBhrB+W9goe6JpDKzzf5+wRgXsElDQ1vvXRdaKRNj65yVpBO9CeceQZ2eYtEZ1js7zbFcJikOsCsHFA1ATYpK9A7UqegFUgK2jBKrONF7y3poXN7nmckri3iFIlUry5D09JDfTE6QfGOi91sNm5xX4xxIWS/pU2WXw5gppcuJiutTi1EZgkCN2bE2AOK7h2LpZn3423K54M22Ht1V9hyyQsAECeajpn2vqh2CBFQNwUdKdd5Mwjsu19+FFRJ/PJkZ/47dtA5nzSnLKxE7DaNL2NFXVyOpTViwRGh35PZ5Ea/3t0YP9ZoQ=,iv:aJio1jxxFlWVTK3xS9JflwjHjLj2iGlzdvUcT0xdH00=,tag:+IOH2U9IVNW3X8O2nD1EZw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZHNQNll2eURwZE44Nkh0
            L1JUTjZmb3NUMnVmaTR1bE1Ib3FxZU1GUkVNCnAyNTQ1QWxwWUNzVkdkNGtkbnl5
            T2ltMU5VWDhWNEgxYmFOTXErSmtSK0EKLS0tIFZTNUhtcENtbDkxdGxpcGlVQ1R4
            ODcrNXVxQ0NwaVFSeCt0cmRBaFg4bkkKkks3niCtqeWXoeG8FZqXLtGLgbrV21BH
            gjtvoarkJtv9YUxu3r0vyQvWcQ8RdiniShgitXDx06v329ykRZtO4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T21:51:20Z"
    mac: ENC[AES256_GCM,data:+hznN/mjxq15oHTk81Cc4rSl+qJmeENR6LT1UWgCFAFsuisvd4E00q0SYa0tDS4rc+l5CTwv99tbPKToAvlVdp44ai4SReIEh1n78A3ZNIKoqvkNQdOD3/dz05fuS3VE8hWQPPDH3jDJ3FHE/lliY+Ossa5Z9QUgK+znS3XE/S8=,iv:pRx+hVtd37ihXXO5PmR8SCe6pIdWh9vaXTwvE8tv1aI=,tag:/ZbAiIUdFTeUU1cVdOBGgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
