apiVersion: v1
data:
    SYMFONY__ENV__SECRET: ENC[AES256_GCM,data:S0fFav3t80UQ/ZI8scqf7EIumrjT5yTGtStxXQPhCMbYfcChB+4z5E5cJLtYF0dPdcPrqeOcssY2a+bRTRVhSFYQI9dldrD8TSoG9sRlVX6XtOqHRiSjgg==,iv:zDvGc1XEZpetCbdXqRZvZSF7QCqvxLZ5ye13iqnRHiM=,tag:V06GukjHKjHvuqX9KGUYJA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: wallabag-env-secret
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNlVNL3lRKzltWFVjcTYz
            TjlsN2ZuWmNNVlJxemV4K0d0ZlFuMUJkNmpJCm9TTHBsMmFRUHB1SEpYdnZUekJk
            cFVrSXNzOFNsbFFtNWJaVUdxMThzSzQKLS0tIEM5SktlZXlHVTV6cFN0eGNVSHBj
            U0RmS2hONlhXV2dDZFZRZ2N6ajFuN1kK7NZO9Nu79RhaMITK47pnNzBjwjEHmFk6
            S6Cl+ch2hfUaQ57mPd7CKBclXDDUezOlCeGUiheWBsJEgREiQu/aSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T21:51:20Z"
    mac: ENC[AES256_GCM,data:IWnbkrpBe3Bf6U8AR73ibtdXADaA9NM/ju/lpwgY8KHXGK3wgiAdxTMe5EuZfsyo6OAC7zd3xJqz1AgubfGVLiixUWu36alsF6uN9ZU4Rm73/84Ks9QGFFSb2pLFY4bKdB7W6mNaGTGJr9yfRRK4+cggP6NF47zrlUfrymf7mCs=,iv:IcLJGkDenkrgmyX6A/4qCGgpKIinxh8YE0EOsPPotr8=,tag:sIg+dPG2xyKP/CFpVt7Dnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
