apiVersion: v1
data:
    SYMFONY__ENV__SECRET: ENC[AES256_GCM,data:h3NT1hnO7rY+x3WyrU9FBuKKwgt8HiaSu/wDGo3InUkaDUJynElfDOnQMjMasQ1FdGEcMHL1tP/lBVSlRMRUOk265oT+4BgdE/5hD+9cx9GAyOR8AfvQrQ==,iv:Or53D18JagSE/h4X834OB6/jvftJx1/K/TSq5FLRH+I=,tag:yo19KvMO8qBLwwRCvfZIrg==,type:str]
    WALLABAG_ADMIN_PASSWORD: ENC[AES256_GCM,data:yhkA/yrBNiXHaGZFsDZezU4T7JZN+3+yPc7IAk6DfLbJrNl5IK/iXA==,iv:62iC3wa7WSFaxHMaaoMygM/gXFE95jCbiQM4m7wNjRA=,tag:n5braZpjLZ+4HOXGdYZSqQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: wallabag-env-secret
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROWNOVzZsLzdIUmkrT1Rj
            bkd4NERHT0h2RTFUM0U4NTZqTkFjMEcxL0hrCktaUVhHeUJKZ0R4alNvYS9aUnVM
            RGNsQk84VmpRUDNCRjJXVVRUTkoyeUEKLS0tIEh1ZnJldWdONzc5bHFDcUlPbWFR
            cTA4WEVUMENsSDRROEs5VVBCeXJGZk0KVZP643K3OdfHGPvIXUaSll4dCa+6f6Xk
            Z7aAo/JKCKmrHVkyhsq7R6HG12XmdB9T6DJdv/erXwY0Iav6A+wyLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T22:30:56Z"
    mac: ENC[AES256_GCM,data:460ZvPgSTvJNz8lzKKNgRq6mZf3DVEynIQNimDxoSL9Nf/KjdMzsgW/TbKv73aEHbcrQfTGx+Rl+iGFkj0Ea0xMsQ7FfgfQRJengSN7dg0pGfoLXKLXvKD2G/g29mlg0JpkkIasrS8O+NXRe7N6Fwm+ljW2tuRjCXheRvjEXdmA=,iv:8SHtHAEMactswEQ2NuWrfQJJaJJz6yyI4yywDuynTkM=,tag:kv8jg7qKPKSuA+73sxjYqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
