apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "66.2.2"

      # version: "58.x"

      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    grafana:
      adminPassword: watary
      ingress:
	enabled: true

	ingressClassName: traefik

	## Hostnames.
	## Must be provided if Ingress is enable.
	##
	# hosts:
	   - grafana.watarystack.org

	## TLS configuration for grafana Ingress
	## Secret must be manually created in the namespace
	##
	tls: []
	# - secretName: grafana-general-tls
	#   hosts:
	#   - grafana.example.com

      # # To make Grafana persistent (Using Statefulset)
      # #
      # persistence:
      #   enabled: true
      #   type: sts
      #   storageClassName: "storageClassName"
      #   accessModes:
      #     - ReadWriteOnce
      #   size: 20Gi
      #   finalizers:
      #     - kubernetes.io/pvc-protection

