apiVersion: v1
data:
    password: ENC[AES256_GCM,data:bB+86mw9Iyh3fbagxZt08pi8yR9V7O79mQT634rMb5egcSDScnsRIj2D7tI=,iv:iSY3b7AHlmpx1fciUwur6UPHgjERinJ/Ed7Uv+au2bo=,tag:qon7AK1BiO4ndCbGBT9J+g==,type:str]
    username: ENC[AES256_GCM,data:m3cwRoMgbp2noKUU,iv:Jq9BGAudnjaY4zrYw2s/lawNN+xBC0iOTodZVy/aSv4=,tag:6ZN4icHhemOdKoIbFQJwyw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: wallabag-db-credentials
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTU0yNmhFcWxTR1Q0aElW
            cmowbE9sOEc5V1dQS0dTcVljbUpsTTdvelNrCjQ4RnhzZnJ0SkNGNDVZYWIvQXgr
            d2YzUlFFbXF1WTZacHl2OE9nUmhqcjgKLS0tIGhzRjNDRUtFeXM1RTcwV0pZYlBM
            enllSTVua29uOGRmZ3BzUkpLWXhkcFUKqUnYCnpyDJ2c3f+4enX+yGGJM3GKx9Pf
            EVLJFZMFIuys5bEYIjQHPRiOMTHUTY9dqGJI25Vwz2Y5VaPEvioGjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T21:52:50Z"
    mac: ENC[AES256_GCM,data:kmjLcQNBKuwAQRCsRnLAlFS8nLNC2LVh6T9wom3j8dgT58eWe70ZYIYt4RW/BOlIVRCCaMvrMmqQMfVXlcr5FNcijKjZokJruJQ4S1MKQkL4fJmLM8Wj5YYPuVPab1l/ekumCfdC6+FtVMUMbIuPgwwUU8H1lzDwtlYvE15htlE=,iv:NYH11j2Wd2tMp0Po9hwSrK+yx5hdNqwql0ETjm+iNOk=,tag:CKFpbH11UMXtKHKyZ+lJVA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
