apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:Te5ZO/NvzjIkQ+6amhIbMQxtzQZyNxYl4aQr34snQDJR+VqFX28IDdD2+Pc=,iv:eI2xFmmlyauoZ2bz903FeC90kG23OSEaoLrh+3q6Bgo=,tag:ji+oegUY2OOg56iNNjdhSw==,type:str]
    ACCESS_KEY_SECRET: ENC[AES256_GCM,data:VEVTp2caknBRA0LB7eUkmk9v/dPUdYOlqiD0XAVdTefx25nKJzd4h3Y9OdIRaxiYLVDnz1M4oHGHQH6uInzzSc8zmYLBZTjmAeLAi72dgGXqXwTvmR473Q==,iv:htxu9n1dVHPcTkPrIpIOxWfj1EDTKrH1iEQXa5q1unI=,tag:ngLbBcSb4sz6TbTlH+9AUg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: wallabag-backup-s3-secret
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRW1DUE9hREVOcndiNkl0
            aG4zSmQ3SFhHbllFZFE3b1h1Vkt1b011a0VNCkpqMFM0Q1RiVVBwcHVGMlVtdjNC
            WkJXakxXL2NDOVg1clJsa2ZiRkVSQlkKLS0tIDh3NmdWR3ZWUmdqTHFFVlN3SEE3
            QlZHNk1TMXFQcXBhcWNJK2xVYVZyNkUK7Ox08izxMepE2jWymIAauyMxTpOhRopj
            BefzXDMMIqoFqFVgiIC4BTmRHD4zCq645xw0tj28G8gz0H/KsgsveA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T21:52:50Z"
    mac: ENC[AES256_GCM,data:wJJTx4GUI5LVawNoDH8OLPKB6KbnCKNh2Yx4IT/gtXsZbDZO7y9UMiqz5PmHXM9WzINEuykeakyftYz0Nty2AJTekcYksQndkR3cnI0zepQ9mUSghDx4dlzsDP29SM6B2sNIFBeCh5f72Sfti4HBzGenJQNqMuIg6BOkU35pPjc=,iv:KsfvUOR5ZtzjuJU2JHUnoW/lJUCcoeReRBQqLqLIVLM=,tag:PZNVzyspZ8X8G6erKGC7og==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
