apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudnativepg-pods
  namespace: monitoring
  labels:
    app.kubernetes.io/name: cloudnativepg
    release: kube-prometheus-stack
spec:
  selector:
    matchExpressions:
      - key: cnpg.io/cluster
        operator: Exists  # Any pod with this label (any CNPG cluster)
  namespaceSelector: {}  # All namespaces
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_cnpg_io_cluster]
          targetLabel: cluster_name
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod_name