apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudnativepg-pods
  namespace: monitoring
  labels:
    app.kubernetes.io/name: cloudnativepg
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: linkding-postgres
  namespaceSelector:
    matchNames:
      - linkding
  podMetricsEndpoints:
    - port: metrics  # Use the named port
      interval: 30s
      path: /metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_cnpg_io_cluster]
          targetLabel: cluster_name
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace