apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:v4V9gaFhc7k=,iv:DA8+5r6t0OT6FahKfLmvGbOrq76M4JAUgzMky0ZdnZk=,tag:lCCvqputSCP5NZo9UFyz3Q==,type:str]
    admin-user: ENC[AES256_GCM,data:SQEHj95ywog=,iv:0uaGSyijQMUE48dX5+azh/y9gpuET6c+pU5HootfcrU=,tag:7+f6nAKjDYo1mwA+YM8uRg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-admin-secret
    namespace: monitoring
sops:
    age:
        - recipient: age1spwc8lctzldd0ghkkls8jfvzzra7cx95r2zqq6eya84etq65wfgqy2h99p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaHgwRmpZa1FsVTVkVThr
            NHVVS0N1enc4WGZqNkNzbW1FS3ZWN1FnVW0wCmo4akNOL0NNR0R0dGk3akJWRU91
            bVZDM2sxZThXOWthd1NMYlozdGVHRkUKLS0tIFUvQUpUUWEzR29kTXJ0WTYvcDI5
            UHZ2Y1pEeFlWNDBPSnFraU95UXdiUTQKd9Nldkey+McQz4B993wTNyrxL1G6PSZk
            nWggwfnpbwBX2VzAb4aS224dFEqFOv4KQjf4TyTQrhzB1VvWkqkTAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T10:44:04Z"
    mac: ENC[AES256_GCM,data:ofGSizjMx2jInWHn2ZLmk7N/w1xzRtcWPoFd9S+Kxfi1pT+jE2eSCyWdnvoWhSHpufGit3LU/vZXf7JMRPY1bQtCQvVptBCV0ijZn/nRkBouzcGCZykjfwVpBqToA7MQ30eL5I3DocXMcIQSmrZTG0lUWke0sigEHo2atLk0Ous=,iv:R3FVVyiirAePOw2UZEUIH7CHbRJj1KeDvoBdAbT0tXg=,tag:YzkSja8xdYxoK9YDwgZfow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
