apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pihole-metrics
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - pihole
  selector:
    matchLabels:
      app.kubernetes.io/name: pihole
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
